version: "3"
services:
  rpc-proxy:
    depends_on:
      - l1_chain
      - deployer
      - l2geth
    image: rpc-proxy
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.rpc-proxy
    environment:
      SEQUENCER: l2geth:8545
      ETH_CALLS_ALLOWED: eth_blockNumber,eth_sendRawTransaction
    ports:
      - 9546:8080
      - 9145:9145
